### PR TITLE
Add Ukrainian language

### PR DESCRIPTION
**Pull request by antonvolokha**
Just added Ukrainian language for Web UI

### CODE REVIEW

**Review by 0purple — COMMENTED** [review]
> Дозволяє рандомизированную
Дозволяє рандомізовану

**Comment by 0purple** [comment]
@spacehuhn Why would you close this PR? Almost no mistakes, good target

**Comment by spacehuhn** [comment]
honestly, I don't remember :( Might have been by accident... Sorry for that. Looks good though! Would you like to open a new one so I can merge it?

**Comment by 0purple** [comment]
Maybe just force push exsisting PR and merge it?

**Comment by spacehuhn** [comment]
I can't merge this PR, but if you don't mind, I can manully add the changes myself.
grafik
grafik

**Comment by 0purple** [comment]
Yeah, that would be good. Also, how any language changes were done since this PR has been created

**Comment by spacehuhn** [comment]
Without checking, I think there were a few. Merged `.in` the other day.

**Pull request closed without merging**
