### PR TITLE
hax0r deauther skin

### PR DESCRIPTION
**Pull request by EnigmaPROGRAMS**
looks pretty h0t tbh

### CODE REVIEW

**Comment by samdenty99** [comment]
Check out a modern version of the deauther — https://github.com/samdenty99/Wi-PWN

**Comment by NurdTurd** [comment]
@EnigmaPROGRAMS all you did was change the color and the font. Personally I like it how it is. No need to add extra bloat just to make it look prettier.

**Comment by EnigmaPROGRAMS** [comment]
@NurdTurd I agree with you, I noticed my 'ignorance' and am now redesigning the UI completely - hopefully you won't see it as bloat when im done lol

**Comment by NurdTurd** [comment]
@EnigmaPROGRAMS Sorry if I said it in a rude manner. It's just adding cool fonts and changing colors doesn't do anything besides make the `.bin`s bigger and the overall project larger.

**Comment by EnigmaPROGRAMS** [comment]
@NurdTurd No it's fine, I understand where you're coming from :)

**Pull request closed without merging**
