### PR TITLE
Minor spelling mistake

### PR DESCRIPTION
**Pull request by Landrash**
Fixes a minor spelling mistake.

### CODE REVIEW

**Comment by samdenty99** [comment]
Is that even a valid *spelling mistake*?  `micro controller` vs `microcontroller`  you removed the header ` What an ESP8266 is` which was linked in the contents. This will probably be closed

**Comment by Landrash** [comment]
@samdenty99 I personally don't care either way. I saw it and submitted a PR and it's up to the author if he or she wants to merge it :slightly_smiling_face:  
I'm a tad unsure about what you believe I removed since this PR is only the removal of a single space?

**Comment by PrinceShaji** [comment]
@Landrash Lil tweaks like these makes the software perfect. :100:

**Comment by spacehuhn** [comment]
Thanks, I'll fix it myself in the testing branch. I'm working on the next update and I don't want to create any unnecessary conflicts between the branches.

**Comment by PrinceShaji** [comment]
@Landrash I'm not complaining, but @spacehuhn has a track record of closing pull request and making the changes himself. Whatever. Don't care what his motives are, but decided to not to make any more contributions. :) 

@Dev: Maybe next time, a pointer on how to contribute would be nice. Probably in the readme.md file. Have a nice day.

**Comment by spacehuhn** [comment]
@PrinceShaji I don't merge PRs for changing 2 or 3 letters, maybe I don't even want to change them. I also got PRs which added typos!
I work on the testing branch and updating the master just creates more conflicts for later merging.
I don't see any reason why anyone should be mad if I fix the one or two typos myself. 

And I don't have time to explain that to everyone, everytime. While I'm explaining the problems with the pull request, I could have just fixed it myself - and that's what I do in these situations.

**Comment by PrinceShaji** [comment]
@spacehuhn Whatever floats your boat bro. Since I've seen people complain about the same, I've added guidelines on how to contribute code in the testing branch. Maybe you would want it, maybe not. Like I said, whatever floats your boat. 

Have a nice day :+1:

**Pull request closed without merging**
