### PR TITLE
Changed webinterface

### PR DESCRIPTION
**Pull request by H1ghTech**
Made a dark Webinterface with material colors

### CODE REVIEW

**Comment by spacehuhn** [comment]
Ok, this is maybe only my opinion but I don't think that's an improvement. Any other opinions on that?

eins
zwei

**Comment by poslogic** [comment]
I personally prefer green to blue.
Here is what I'm using.

deauther

**Comment by H1ghTech** [comment]
Maybe​ you could add a setting to choose a theme (will only work for ESP's with enough memory)

**Comment by spacehuhn** [comment]
OK I also think we let it as it is and everybody can customize it themselves if they want.

**Pull request closed without merging**
