### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by samdenty99**

### CODE REVIEW

**Comment by tobozo** [comment]
Thanks! 
No need to delete the text now :+1:

**Comment by spacehuhn** [comment]
but now you removed a noob filter

**Comment by tobozo** [comment]
in that case the repo needs a code of conduct too :book:

**Comment by samdenty99** [comment]
You can always click on the edit button to see if they left it in or not
image

**Comment by spacehuhn** [comment]
So I thought about this and seeing that it works, I want to keep it as it is.
People should be intelligent enough (or have the attention span required) to read, understand and follow the simple instruction given by the default text. If not, it's at least publicly visible and automatically tells us that the person didn't follow the instructions.

**Pull request closed without merging**
