### PR TITLE
canged info.html a tiny bit

### PR DESCRIPTION
**Pull request by willem640**
added links at the bottom instead of raw text

### CODE REVIEW

**Comment by willem640** [comment]
i also changed the data.h, but it is not showing :(
here it is showing i think:
https://github.com/spacehuhn/esp8266_deauther/pull/573.patch

**Comment by willem640** [comment]
it is being a little weird, i am going to recommit this and hopefully fix it

**Comment by spacehuhn** [comment]
First of all: pull requests only into the testing branch please (https://github.com/spacehuhn/esp8266_deauther/blob/master/CONTRIBUTING.md) !
And secondly, the links that you made clickable were plaintext for a reason.
I made this decision on purpose and I don't want to change that.

I hope you understand this.

**Comment by willem640** [comment]
Okay, I apologise for that, maybe it would be a good idea if I looked in the contributing.md file :(

**Comment by spacehuhn** [comment]
No big deal, just that you know for next time :)

**Pull request closed without merging**
