### PR TITLE
Add Chinese lang support

### PR DESCRIPTION
**Pull request by Henvy-Mango**
A Chinese web interface.

### CODE REVIEW

**Comment by Henvy-Mango** [comment]
It seems that the language.h does not support Chinese language font.So the cn.lang can not work,but other lang files can work perfectly.
I guess it if use the Unicode might fix the problem.

**Comment by spacehuhn** [comment]
The display font only supports alphanumeric characters, so that won't work. I will look into alternatives but other things have priority right now.
Thanks for making the translation for the web interface!

**Comment by spacehuhn** [comment]
Oh another thing before I merge it. Please open an issue about it, so other people can contribute more easily to your translation. Like I did for the German translation or others for French and Czech.

**Comment by Henvy-Mango** [comment]
Sure:D

**Pull request merged**
